# Generated by Django 4.2.4 on 2023-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='a', max_length=6, unique=True, verbose_name='Invite code пользователя'),
            preserve_default=False,
        ),
    ]
