# Generated by Django 4.2.4 on 2023-08-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=6, verbose_name='Invite code пользователя'),
        ),
    ]
