# Generated by Django 4.2.4 on 2023-08-18 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_active_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_user_userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
